kind: pipeline
name: default

steps:
- name: dockerhub
  image: plugins/docker
  settings:
    repo: kexpress/louis
    dockerfile: build/drone.dockerfile
    tags:
      - latest
      - ${DRONE_TAG}
      - ${DRONE_COMMIT_SHA}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - tag