language: go
sudo: enabled
dist: trusty
  
go:
  - "1.10.x"

services:
  - redis
  - postgresql
  - docker

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6
    - postgresql-client-9.6

env:
  - REDIS_URL=127.0.0.1:6379 POSTGRES_DATABASE=travis_ci_test CLEANUP_DELAY=1 POSTGRES_ADDRESS=127.0.0.1:5432 LOUIS_PUBLIC_KEY=pkey LOUIS_SECRET_KEY=skey POSTGRES_SSL_MODE=disable

before_install:
  # install dependencies for bimg
  - curl -s https://raw.githubusercontent.com/h2non/bimg/master/preinstall.sh | sudo bash -

# install: 
  # - dep ensure

script: 
  - go test

before_script:
  - sudo chmod 777 test/data
  # - sudo chown www-data test/data
  - psql -c 'create database travis_ci_test;' -U postgres
