language: go
sudo: enabled
dist: trusty
  
go:
  - "1.10.x"

services:
  - redis
  - postgres

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6
    - postgresql-client-9.6

env:
  - REDIS_URL=127.0.0.1:6379 POSTGRES_DATABASE=travis_ci_test CLEANUP_DELAY=1 

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  # install dependencies for bimg
  - curl -s https://raw.githubusercontent.com/h2non/bimg/master/preinstall.sh | sudo bash -

before_script:
  - sudo chmod 777 test/data
  # - sudo chown www-data test/data
  - psql -c 'create database travis_ci_test;' -U postgres

after_script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
